create database customer_Shopping_behaviour;
USE customer_Shopping_behaviour;
SELECT * FROM products;

-- 1) What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM products
GROUP BY gender;

-- 2) Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM products
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM products);

-- 3) Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS avg_rating
FROM products
GROUP BY item_purchased 
ORDER BY avg_rating DESC 
LIMIT 5;

-- 4) Compare the average purchase amount between standard and express shipping?
SELECT shipping_type, ROUND(AVG(purchase_amount),2) 
FROM products
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- 5) Do subscribed customers spend more? 
-- Compare average spend And totl revenue between subscribers and non-subscribers.alter
SELECT subscription_status,
COUNT(customer_id) AS total_customer,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM products
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- 6) Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
ROUND(100 * SUM( CASE WHEN discount_applied = 'Yes'THEN 1 ELSE 0 END) /COUNT(*),2) AS discount_rate
FROM products
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7) Segment customer into new, returning and loyal based
 -- on their total number of previous purchase, and show the count of each segment?

SELECT 
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS segment_count
FROM products
GROUP BY customer_segment;

-- 8) What are the top 3 most purchases products within each category?
SELECT 
    category,
    item_purchased,
    total_purchases
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rank_in_category
    FROM products
    GROUP BY category, item_purchased
) ranked
WHERE rank_in_category <= 3
ORDER BY category, rank_in_category;

-- 9) Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM products
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10) What is the revenue contribution of each age group?
SELECT age_group, 
SUM(purchase_amount) AS total_revenue
FROM products
GROUP BY age_group
ORDER BY total_revenue DESC;